services:
  app:
    container_name: basic-chat-client
    build: .
    ports:
      - "${DOCKER_NODEJS_PORT:-3000}:3000"
    volumes:
      - ./src:/usr/src/app
      - /usr/src/app/node_modules
    environment:
      HOST: 0.0.0.0
      VITE_API_URL: "${VITE_API_URL:-http://localhost:97}"
    networks:
      - default-network
networks:
  default-network:
    name: basic-chat-network
    driver: bridge
